# Generated by Django 5.2.3 on 2026-06-26 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=20)),
                ('payment_type', models.CharField(choices=[('pix', 'Pix'), ('credit', 'Crédito'), ('debit', 'Débito')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('installments', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
